# my global config
global:
  scrape_interval:     1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.


   - job_name: 'cpu_usages'
     static_configs:
#      - targets: ['ftp:9100']
      - targets: ['jenkins.root.com:9100']
      - targets: ['sensu.root.com:9100']
      - targets: ['ansible.root.com:9100']
      - targets: ['ftp.root.com:9100']
      - targets: ['salt.root.com:9100']
      - targets: ['grafana.root.com:9100']
      - targets: ['k8.root.com:9100']
      - targets: ['docker.root.com:9100']
#      - targets: ['windows:9100']
#      - targets: ['test22:9100']
      - targets: ['worker1.root.com:9100']
#      - targets: ['worker2:9100']
      - targets: ['dhcp.root.com:9100']
      - targets: ['pxe.root.com:9100']
      - targets: ['elastic.root.com:9100']
      - targets: ['kibana.root.com:9100']
      - targets: ['logstash.root.com:9100']
   - job_name: jenkins_info
     scrape_interval: 1s
     scrape_timeout: 1s
     metrics_path: /prometheus
     scheme: http
     static_configs:
      - targets:
        - jenkins.root.com:8080
   - job_name: dhcp
     scrape_interval: 1s
     scrape_timeout: 1s
     metrics_path: /metrics
     scheme: http
     static_configs:
      - targets:
        - dhcp:9091